tap "carlocab/personal"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "knqyf263/trivy"
tap "liamg/tfsec"
tap "seiji/formulas"
tap "simnalamburt/x"
brew "amazon-ecs-cli"
brew "ansible"
brew "antigen"
brew "apache-spark"
brew "asciidoctor"
brew "autoconf"
brew "automake"
brew "aws-sam-cli"
brew "awscli"
brew "awslogs"
brew "azure-cli"
brew "carlocab/personal/unrar"
brew "circleci"
brew "cloc"
brew "colordiff"
brew "conftest"
brew "container-diff"
brew "copilot"
brew "coreutils"
brew "dhall"
brew "dhall-json"
brew "dhall-lsp-server"
brew "direnv"
brew "editorconfig"
brew "eksctl"
brew "exercism"
brew "fzf"
brew "gettext"
brew "gh"
brew "gibo"
brew "gist"
brew "git"
brew "git-secrets"
brew "glib"
brew "gnu-sed"
brew "gnupg"
brew "gnutls"
brew "go"
brew "goenv", args: ["HEAD"]
brew "golangci-lint"
brew "grep"
brew "guile"
brew "hashicorp/tap/terraform-ls"
brew "hugo"
brew "iproute2mac"
brew "jq"
brew "knqyf263/trivy/trivy"
brew "krb5"
brew "kubernetes-cli"
brew "ldns"
brew "liamg/tfsec/tfsec"
brew "libpq"
brew "llvm"
brew "luajit", args: ["HEAD"]
brew "mas" if OS.mac?
brew "maven"
brew "navi"
brew "neovim"
brew "nghttp2"
brew "ninja"
brew "nmap"
brew "node-build"
brew "nodenv"
brew "opa"
brew "openjdk"
brew "openssh"
brew "perl"
brew "pinentry-mac" if OS.mac?
brew "pixman"
brew "pkg-config"
brew "pwgen"
brew "pyenv"
brew "python@3.9"
brew "rbenv"
brew "ripgrep"
brew "rlwrap"
brew "ruby"
brew "ruby-build"
brew "rustup-init"
brew "seiji/formulas/aws-sessionmanager"
#brew "seiji/formulas/goss"
brew "seiji/formulas/terragrunt"
brew "shared-mime-info"
brew "smug"
brew "source-highlight"
brew "sphinx-doc"
brew "st"
brew "stow"
brew "tealdeer"
brew "telnet"
brew "terraformer"
brew "terrascan"
brew "tfenv"
brew "tflint"
brew "tfupdate"
brew "tig"
brew "tmux"
brew "tree"
brew "unbound"
brew "vegeta"
brew "vim"
brew "watch"
brew "websocat"
brew "weechat"
brew "wget"
brew "xsv"
brew "ykman"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "1password"
cask "alacritty"
cask "alfred"
cask "amazon-workspaces"
cask "amorphousdiskmark"
cask "arduino"
cask "aws-vault"
cask "brave-browser"
cask "cinebench"
cask "cloudflare-warp"
cask "coteditor"
cask "dash"
cask "deepl"
cask "discord"
cask "docker"
cask "drawio"
cask "dropbox"
cask "figma"
cask "firefox"
cask "font-ricty-diminished"
cask "forklift"
cask "ghostty"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "hex-fiend"
cask "keybase"
cask "kindle"
cask "macs-fan-control"
cask "mendeley"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "microsoft-remote-desktop"
cask "mitmproxy"
cask "notion"
cask "obsidian"
cask "path-finder"
cask "rectangle"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "tableplus"
cask "transmit"
cask "typora"
cask "uhk-agent"
cask "visual-studio-code"
cask "zoom"
mas "Apple Configurator", id: 1037126344
mas "Diagrams", id: 1276248849
mas "Fotor Photo Editor", id: 503039729
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LanScan", id: 472226235
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Okta Verify", id: 490179405
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "Type Fu", id: 509818877
mas "Xcode", id: 497799835
