(require 'tramp)
(setq tramp-default-method "ssh")
;(setf tramp-shell-prompt-pattern "^[^#$>n]*[#$%>] *(0-9}*[a-zA-Z] *)*")
;(setq shell-prompt-pattern "^[ $%]+")
;(setq tramp-shell-prompt-pattern "^.*[#$%>] *")
(setq tramp-debug-buffer t)
(setq tramp-shell-prompt-pattern "^.*[#＼$%>] *")
(setq tramp-verbose 10)
(setq vc-handled-backends nil)
(setq ls-lisp-use-insert-directory-program t)     
