(require 'navi2ch)
(setq navi2ch-ask-when-exit nil)
(setq navi2ch-message-user-name "")
(setq navi2ch-net-save-old-file-when-aborn nil)
(setq navi2ch-message-ask-before-send nil)
(setq navi2ch-message-ask-before-kill nil)
(setq navi2ch-article-max-buffers 5)
(setq navi2ch-article-auto-expunge t)
(setq navi2ch-board-insert-subject-with-diff t)
(setq navi2ch-board-insert-subject-with-unread t)
(setq navi2ch-article-exist-message-range '(1 . 1000))
(setq navi2ch-article-new-message-range '(1000 . 1))
(setq navi2ch-list-stay-list-window t)
